package com.dtsx.dh.commands.docs.test;

import com.dtsx.dh.config.ctx.BaseCtx;
import com.dtsx.dh.config.ctx.BaseScriptRunnerCtx;
import com.dtsx.dh.core.docs.runner.drivers.ClientDriver;
import com.dtsx.dh.core.common.ClientLanguage;
import com.dtsx.dh.core.docs.runner.tests.VerifyMode;
import com.dtsx.dh.core.docs.runner.tests.reporter.TestReporter;
import com.dtsx.dh.lib.ExternalPrograms;
import com.dtsx.dh.lib.ExternalPrograms.ExternalProgram;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.val;
import org.jetbrains.annotations.MustBeInvokedByOverriders;
import picocli.CommandLine;
import picocli.CommandLine.Model.CommandSpec;

import java.nio.file.Path;
import java.util.*;
import java.util.function.Function;
import java.util.function.Predicate;

import static com.dtsx.dh.core.docs.runner.tests.VerifyMode.DRY_RUN;

/// **Note: Docs for this class were generated by AI**
///
/// The runtime context for the verifier, containing all configuration and dependencies needed to run tests.
///
/// Built from [DocsTestArgs] via `args.toCtx(spec)`, this validates everything is set up correctly:
/// - Database connection info (token + endpoint)
/// - Examples folder exists with required `_base/` and `_fixtures/` subdirectories
/// - All required external programs are installed (tsx, npm, language-specific tools)
/// - Client drivers are configured with correct artifact versions
///
/// @see DocsTestArgs
@Getter
public class DocsTestCtx extends BaseScriptRunnerCtx {
    @Getter(AccessLevel.NONE)
    private final Map<ClientLanguage, ClientDriver> drivers;

    private final TestReporter reporter;
    private final VerifyMode verifyMode;
    private final Predicate<Path> filter;
    private final int maxFixtureInstances;

    public List<ClientDriver> drivers() {
        return new ArrayList<>(drivers.values());
    }

    public ClientDriver driver(ClientLanguage lang) {
        return drivers.get(lang);
    }

    public List<ClientLanguage> languages() {
        return new ArrayList<>(drivers.keySet());
    }

    public DocsTestCtx(DocsTestArgs args, CommandSpec spec) {
        super(args, spec);
        this.drivers = mkDrivers(cmd, args);
        this.reporter = args.$reporter.create(this);
        this.verifyMode = resolveVerifyMode(args);
        this.filter = mkFilter(args);
        this.maxFixtureInstances = args.$maxFixtureInstances;
    }

    @Override
    @MustBeInvokedByOverriders
    protected Set<Function<BaseCtx, ExternalProgram>> requiredPrograms() {
        return new HashSet<>(super.requiredPrograms()) {{
            add(ExternalPrograms::npm);

            for (val driver : drivers.values()) {
                addAll(driver.requiredPrograms());
            }
        }};
    }

    private Map<ClientLanguage, ClientDriver> mkDrivers(CommandLine cmd, DocsTestArgs args) {
        val driversMap = new HashMap<ClientLanguage, ClientDriver>();

        for (val lang : args.$drivers.resolve()) {
            val driver = mkDriverForLanguage(cmd, lang, args);
            driversMap.put(lang, driver);
        }

        return driversMap;
    }

    private VerifyMode resolveVerifyMode(DocsTestArgs args) {
        return (args.$dryRun)
            ? DRY_RUN
            : args.$verifyMode;
    }

    private Predicate<Path> mkFilter(DocsTestArgs args) {
        val includePredicate = mkFilterPredicates(args.$filters, args.$fand)
            .orElse(_ -> true);

        val excludePredicate = mkFilterPredicates(args.$inverseFilters, args.$fand)
            .map(Predicate::negate)
            .orElse(_ -> true);

        return includePredicate.and(excludePredicate);
    }

    private Optional<Predicate<Path>> mkFilterPredicates(List<String> filter, boolean and) {
        return filter.stream()
            .map(String::trim)
            .filter(s -> !s.isBlank())
            .map((s) -> (Predicate<Path>) (path) -> path.toString().matches(".*" + s + ".*"))
            .reduce(and ? Predicate::and : Predicate::or);
    }
}
