inputs:
  clients:
    description: 'Comma-separated list of client drivers to test (e.g., java,typescript,python) or "all" for all clients'
    required: true
  docs-repo:
    description: 'Documentation repository in format [org/repo][@branch] (both the org/repo and branch are optional)'
    default: 'riptano/astra-vector-docs@main'
  docs-repo-token:
    description: 'GitHub PAT with access to the docs repository (if internal/private, otherwise not needed)'
    required: true
  examples-path:
    description: 'Path to examples folder within the docs repository (defaults to modules/api-reference/examples)'
    default: 'modules/api-reference/examples'
  args:
    description: 'Additional arguments to pass to dh'
    default: ''
  db-token:
    description: 'Astra token for authentication'
    required: true
  db-endpoint:
    description: 'API endpoint for testing'
    required: true
  allow-failures:
    description: 'Whether to allow test failures without failing the entire workflow'
    default: 'false'

outputs:
  failed_tests:
    description: 'Whether any tests failed'
    value: ${{ steps.run-tests.outputs.failed_tests }}

runs:
  using: composite
  steps:
    - name: Checkout docs testing repository
      uses: actions/checkout@v4
      with:
        repository: 'datastax/astra-client-docs-tests'
        path: astra-client-docs-tests

    - name: Setup docs env
      uses: ./astra-client-docs-tests/.github/actions/_setup-docs-env
      with:
        docs-repo: ${{ inputs.docs-repo }}
        docs-repo-token: ${{ inputs.docs-repo-token }}
        examples-path: ${{ inputs.examples-path }}
        setup-languages: ${{ inputs.clients }},typescript # always need typescript for execution tests
        setup-jq: true

    - name: Run client compilation tests
      id: run-tests
      uses: ./astra-client-docs-tests/.github/actions/_use-dh
      env:
        ASTRA_TOKEN: ${{ inputs.db-token }}
        API_ENDPOINT: ${{ inputs.db-endpoint }}
      with:
        allow-failures: ${{ inputs.allow-failures }}
        args: |
          docs test ${{ inputs.clients }} ${{ inputs.args }}
