package com.dtsx.dh.lib;

import com.dtsx.dh.config.ctx.BaseCtx;
import com.dtsx.dh.core.common.CliException;
import lombok.RequiredArgsConstructor;
import lombok.val;
import org.apache.commons.lang3.ArrayUtils;
import org.jetbrains.annotations.Nullable;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Path;
import java.util.*;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.regex.Pattern;

import static com.dtsx.dh.lib.ExternalPrograms.ExternalProgramType.*;

/// **Note: Docs for this class were generated by AI**
///
/// Factory for creating [ExternalProgram] instances with command overrides from [BaseCtx].
///
/// Each program can be overridden via environment variables (e.g., `TSX_COMMAND=npx -y tsx`)
/// or CLI flags (e.g., `-Ctsx='npx -y tsx'`), falling back to sensible defaults.
public class ExternalPrograms {
    /// Returns a tsx executor (default: `npx -y tsx`).
    ///
    /// Used to run JavaScript fixtures and TypeScript test files.
    public static ExternalProgram tsx(BaseCtx ctx) {
        return get(TSX, ctx);
    }

    /// Returns an npm executor (default: `npm`).
    ///
    /// Used to install dependencies for fixtures and execution environments.
    public static ExternalProgram npm(BaseCtx ctx) {
        return get(NPM, ctx);
    }

    /// Returns a bash executor (default: `bash`).
    ///
    /// Used to run bash example scripts.
    public static ExternalProgram bash(BaseCtx ctx) {
        return get(BASH, ctx);
    }

    /// Returns a python executor (default: `python3`).
    ///
    /// Used to run Python example scripts.
    public static ExternalProgram python(BaseCtx ctx) {
        return get(PYTHON, ctx);
    }

    /// Returns a java executor (default: `java`).
    ///
    /// Used to run compiled Java example classes.
    public static ExternalProgram java(BaseCtx ctx) {
        return get(JAVA, ctx);
    }

    /// Returns a dotnet executor (default: `dotnet`).
    ///
    /// Used to run C# example scripts.
    public static ExternalProgram dotnet(BaseCtx ctx) {
        return get(DOTNET, ctx);
    }

    /// Returns a dotnet executor that must have an 8.x SDK installed, for repos pinning `net8.0`.
    ///
    /// `--list-sdks` is the probe rather than `--version`, which reports whichever SDK the current
    /// directory's `global.json` selected and fails outright when that one is absent.
    public static ExternalProgram dotnet8(BaseCtx ctx) {
        return get(DOTNET, ctx, DOTNET_8_SDK);
    }

    private static final Pattern DOTNET_8_SDK_PATTERN = Pattern.compile("(?m)^8\\.\\d");

    private static final Requirement DOTNET_8_SDK = new Requirement(
        List.of("--list-sdks"),
        (output) -> DOTNET_8_SDK_PATTERN.matcher(output).find(),
        "an 8.x .NET SDK"
    );

    /// Returns a jq executor (default: `jq`).
    ///
    /// Used to further refine JSON.
    public static ExternalProgram jq(BaseCtx ctx) {
        return get(JQ, ctx);
    }

    /// Returns a go executor (default: `go`).
    ///
    /// Used to run Go example scripts.
    public static ExternalProgram go(BaseCtx ctx) {
        return get(GO, ctx);
    }

    /// Returns a git executor (default: `git`).
    ///
    /// Used to clone client repos for `dh clients test`.
    public static ExternalProgram git(BaseCtx ctx) {
        return get(GIT, ctx);
    }

    /// Returns a mvn executor (default: `mvn`).
    ///
    /// Used to run the java client's integration suite.
    public static ExternalProgram mvn(BaseCtx ctx) {
        return get(MVN, ctx);
    }

    /// Returns a uv executor (default: `uv`).
    ///
    /// Used to install dependencies and run astrapy's integration suite.
    public static ExternalProgram uv(BaseCtx ctx) {
        return get(UV, ctx);
    }

    /// Returns a node executor (default: `node`).
    ///
    /// Used to run the TypeScript toolchain.
    public static ExternalProgram node(BaseCtx ctx) {
        return get(NODE, ctx);
    }

    /// Returns a custom executor with no default command.
    ///
    /// Useful for calling definitely-available scripts (such as `./.gradlew`)
    public static ExternalProgram custom() {
        return new ExternalProgram("custom", new String[0], Optional.empty());
    }

    private static ExternalProgram get(ExternalProgramType type, BaseCtx ctx) {
        return get(type, ctx, type.requirement);
    }

    /// Builds a program from `type`, overriding [ExternalProgramType#requirement] with `requirement`
    /// - for a caller that needs something more specific than that entry's own (global) requirement.
    private static ExternalProgram get(ExternalProgramType type, BaseCtx ctx, @Nullable Requirement requirement) {
        return new ExternalProgram(
            type.name().toLowerCase(),
            ctx.commandOverrides().getOrDefault(type, type.defaultCommand()),
            Optional.of(type.existsCheckArg),
            Optional.ofNullable(requirement)
        );
    }

    private static final Pattern VERSION_PATTERN = Pattern.compile("(\\d+)\\.(\\d+)(?:\\.(\\d+))?");

    /// Builds a [Requirement] matching output containing a `major.minor[.patch]` version at least as
    /// high as the one given (the first such pattern found in the output, e.g. within
    /// `go version go1.23.4 darwin/arm64`), probed with `probeArg`.
    private static Requirement minVersion(String probeArg, int minMajor, int minMinor, int minPatch) {
        Predicate<String> predicate = (output) -> {
            val matcher = VERSION_PATTERN.matcher(output);

            if (!matcher.find()) {
                return false;
            }

            val major = Integer.parseInt(matcher.group(1));
            val minor = Integer.parseInt(matcher.group(2));
            val patch = (matcher.group(3) != null) ? Integer.parseInt(matcher.group(3)) : 0;

            if (major != minMajor) return major > minMajor;
            if (minor != minMinor) return minor > minMinor;
            return patch >= minPatch;
        };

        return new Requirement(List.of(probeArg), predicate, "version >= " + minMajor + "." + minMinor + "." + minPatch);
    }

    /// One requirement a program's exists-check output must satisfy: `probeArgs` are run against the
    /// program in place of its plain exists-check, and `predicate` is tested against the combined
    /// output. `describe` is a short phrase for what's required (e.g. `version >= 1.23.0`, `an 8.x
    /// .NET SDK`) - it must not repeat the remedy [BaseCtx#verifyRequiredProgramsAvailable] already
    /// appends.
    public record Requirement(List<String> probeArgs, Predicate<String> predicate, String describe) {}

    /// Enum of external programs with their default commands.
    ///
    /// Each can be overridden via `<NAME>_COMMAND` env var (e.g., `TSX_COMMAND=bun tsx`).
    @RequiredArgsConstructor
    public enum ExternalProgramType {
        TSX("npx -y tsx", "--version", null),
        NPM("npm", "--version", null),
        BASH("bash", "--version", null),
        PYTHON("python3", "--version", minVersion("--version", 3, 10, 0)),
        JAVA("java", "--version", minVersion("--version", 17, 0, 0)),
        DOTNET("dotnet", "--version", null),
        JQ("jq", "--version", null),
        GO("go", "version", minVersion("version", 1, 23, 0)),
        GIT("git", "--version", null),
        NODE("node", "--version", minVersion("--version", 18, 0, 0)),
        UV("uv", "--version", null),
        MVN("mvn", "--version", minVersion("--version", 3, 6, 3));

        private final String defaultCommand;
        private final String existsCheckArg;

        /// Requirement checked against the exists-check output, or `null` to only check presence.
        private final @Nullable Requirement requirement;

        public String[] defaultCommand() {
            return defaultCommand.split(" ");
        }
    }

    /// Represents a line of output from a program, tagged as stdout or stderr.
    public sealed interface OutputLine { String unwrap(); }
    
    /// A line from stdout.
    public record StdoutLine(String unwrap) implements OutputLine {}
    
    /// A line from stderr.
    public record StderrLine(String unwrap) implements OutputLine {}

    /// Result of running an external program.
    ///
    /// Captures exit code and all output lines (stdout and stderr) in the order they were produced.
    ///
    /// Example:
    /// ```java
    /// val result = tsx.run("script.ts");
    /// if (result.exitCode() != 0) {
    ///     System.err.println(result.stderr());
    /// }
    /// ```
    public record RunResult(int exitCode, List<OutputLine> outputLines) {
        /// Returns only stdout as a single string.
        public String stdout() {
            return buildOutput(StdoutLine.class::isInstance);
        }

        /// Returns only stderr as a single string.
        public String stderr() {
            return buildOutput(StderrLine.class::isInstance);
        }

        /// Returns both stdout and stderr interleaved in the order they were produced.
        public String output() {
            return buildOutput(_ -> true);
        }

        ///  Returns true if the exit code is 0.
        public boolean ok() {
            return exitCode == 0;
        }

        /// Returns false if the exit code is 0.
        public boolean notOk() {
            return exitCode != 0;
        }

        private String buildOutput(Predicate<OutputLine> filter) {
            val sb = new StringBuilder();
            for (val line : outputLines) {
                if (filter.test(line)) {
                    sb.append(line.unwrap());
                }
            }
            return sb.toString();
        }
    }

    /// An external program that can be executed with arguments.
    ///
    /// Automatically injects environment variables (API endpoint, token, etc.) into the process.
    ///
    /// Example:
    /// ```java
    /// val tsx = ExternalPrograms.tsx(ctx);
    /// val result = tsx.run(Path.of("/tmp"), "script.ts", "--verbose");
    /// ```
    public record ExternalProgram(String name, String[] cmd, Optional<String> existsCheckArg, Optional<Requirement> requirement) {
        public ExternalProgram(String name, String[] cmd, Optional<String> existsCheckArg) {
            this(name, cmd, existsCheckArg, Optional.empty());
        }

        /// Runs the program with the given arguments in the current directory.
        ///
        /// Standard placeholder env vars (`API_ENDPOINT`, `ASTRA_TOKEN`, etc.) are automatically injected.
        ///
        /// @param args command-line arguments to pass to the program
        /// @return the result containing exit code and output
        public RunResult run(String... args) {
            return run(null, args);
        }

        /// Runs the program with the given arguments in a specific directory.
        ///
        /// Standard placeholder env vars (`API_ENDPOINT`, `ASTRA_TOKEN`, etc.) are automatically injected.
        ///
        /// @param workingDir the working directory (null for current directory)
        /// @param args command-line arguments to pass to the program
        /// @return the result containing exit code and output
        public RunResult run(@Nullable Path workingDir, String... args) {
            return run(workingDir, null, args);
        }

        /// Runs the program with the given arguments in a specific directory and environment variables.
        ///
        /// Standard placeholder env vars (`API_ENDPOINT`, `ASTRA_TOKEN`, etc.) are automatically injected.
        ///
        /// @param workingDir the working directory (null for current directory)
        /// @param envVars additional environment variables to set (null for nne)
        /// @param args command-line arguments to pass to the program
        /// @return the result containing exit code and output
        public RunResult run(@Nullable Path workingDir, @Nullable Map<String, String> envVars, String... args) {
            return run(workingDir, envVars, null, args);
        }

        /// Runs the program with the given arguments in a specific directory and environment
        /// variables, invoking `onLine` for each line of output as it arrives.
        ///
        /// `onLine` is called from both the stdout- and stderr-reading threads, potentially
        /// concurrently, so it must be thread-safe.
        ///
        /// Standard placeholder env vars (`API_ENDPOINT`, `ASTRA_TOKEN`, etc.) are automatically injected.
        ///
        /// @param workingDir the working directory (null for current directory)
        /// @param envVars additional environment variables to set (null for nne)
        /// @param onLine called for each line of output as it is produced (null to skip)
        /// @param args command-line arguments to pass to the program
        /// @return the result containing exit code and output
        public RunResult run(@Nullable Path workingDir, @Nullable Map<String, String> envVars, @Nullable Consumer<OutputLine> onLine, String... args) {
            try {
                val process = startProcess(workingDir, ArrayUtils.addAll(cmd, args), envVars);

                val outputLines = Collections.synchronizedList(new ArrayList<OutputLine>());

                val stdoutReaderThread = Thread.startVirtualThread(mkStreamReader(process.getInputStream(), outputLines, StdoutLine::new, onLine));
                val stderrReaderThread = Thread.startVirtualThread(mkStreamReader(process.getErrorStream(), outputLines, StderrLine::new, onLine));

                val exitCode = process.waitFor();

                stdoutReaderThread.join();
                stderrReaderThread.join();

                return new RunResult(exitCode, outputLines);
            } catch (IOException | InterruptedException e) {
                CliLogger.exception(e);
                Thread.currentThread().interrupt();
                return new RunResult(-1, List.of(new StderrLine(e.toString())));
            }
        }

        /// Runs the program with the given arguments in a specific directory, throwing a
        /// [CliException] naming the program, its args and its output if the exit code is non-zero.
        ///
        /// @param workingDir the working directory (null for current directory)
        /// @param args command-line arguments to pass to the program
        /// @return the result containing exit code and output
        public RunResult runOrThrow(@Nullable Path workingDir, String... args) {
            val result = run(workingDir, args);

            if (result.notOk()) {
                throw new CliException(name + " " + String.join(" ", args) + " failed:\n" + result.output());
            }

            return result;
        }

        /// Runs the program with the given arguments in the current directory, throwing a
        /// [CliException] naming the program, its args and its output if the exit code is non-zero.
        ///
        /// @param args command-line arguments to pass to the program
        /// @return the result containing exit code and output
        public RunResult runOrThrow(String... args) {
            return runOrThrow(null, args);
        }

        /// Checks whether the program exists, is executable, and (when [#requirement] is present)
        /// satisfies it, by running a single probe - [Requirement#probeArgs] when a requirement is
        /// present, else `<program> <existsCheckArg>` - and inspecting its output.
        ///
        /// @return empty if the program is usable, otherwise a short lower-case phrase describing
        /// the failure
        public Optional<String> problem() {
            val probeArgs = requirement.map(Requirement::probeArgs).or(() -> existsCheckArg.map(List::of));

            if (probeArgs.isEmpty()) {
                return Optional.empty();
            }

            val result = run(probeArgs.get().toArray(new String[0]));

            if (result.notOk()) {
                return Optional.of("could not be found");
            }

            return requirement
                .filter((req) -> !req.predicate().test(result.output()))
                .map((req) -> "requires " + req.describe());
        }

        /// Returns the environment variable name used to override this program's command.
        ///
        /// For example, `tsx` returns `TSX_COMMAND`, `python` returns `PYTHON_COMMAND`.
        ///
        /// @return the environment variable name (e.g., "TSX_COMMAND")
        public String envVar() {
            return name.toUpperCase() + "_COMMAND";
        }

        private Process startProcess(Path dir, String[] fullCmd, @Nullable Map<String, String> envVars) throws IOException {
            val pb = new ProcessBuilder(fullCmd);

            if (dir != null) {
                pb.directory(dir.toFile());
            }

            if (envVars != null) {
                pb.environment().putAll(envVars);
            }

            return pb.start();
        }

        private Runnable mkStreamReader(InputStream stream, List<OutputLine> outputLines, Function<String, OutputLine> mapper, @Nullable Consumer<OutputLine> onLine) {
            return () -> {
                try (val reader = new BufferedReader(new InputStreamReader(stream))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        val outputLine = mapper.apply(line + System.lineSeparator());
                        outputLines.add(outputLine);
                        if (onLine != null) {
                            onLine.accept(outputLine);
                        }
                    }
                } catch (IOException ignored) {}
            };
        }

        @Override
        public boolean equals(Object obj) {
            return obj instanceof ExternalProgram other && this.name.equals(other.name);
        }

        @Override
        public int hashCode() {
            return name.hashCode();
        }
    }
}
